In [1]:
# One dimensional arrray
import numpy as np

one_dimensional_array = np.array([1.2, 2.4, 3.5, 4.7, 6.1, 7.2, 8.3, 9.5])
print(one_dimensional_array)

[1.2 2.4 3.5 4.7 6.1 7.2 8.3 9.5]


In [2]:
# Two dimentional array
# You can also use np.array to create a two-dimensional array. 
# To create a two-dimensional array specify an extra layer of square brackets. For example, the following call creates a 3x2 array:
import numpy as np
two_dimensional_array = np.array([[6, 5], [11, 7], [4, 8]])
print(two_dimensional_array)

[[ 6  5]
 [11  7]
 [ 4  8]]


In [5]:
# Populate arrays with sequences of numbers
# You can populate an array with a sequence of numbers

import numpy as np
sequence_of_integers = np.arange(5, 12)
print(sequence_of_integers)

# Notice that np.arange generates a sequence that includes 
# the lower bound (5) but not the upper bound (12).

[ 5  6  7  8  9 10 11]


In [22]:
# Populate arrays with random numbers
# NumPy provides various functions to populate arrays with random numbers across certain ranges. 
# For example, np.random.randint generates random integers between a low and high value. 
# The following call populates a
# 6-element array with random integers between 50 and 100.

import numpy as np
random_integers_between_50_and_100 = np.random.randint(low=50, high=101, size=6)
print(random_integers_between_50_and_100)

# Note that the highest generated integer np.random.randint is one less than the high argument.

[51 63 65 87 54 85]


In [16]:
# To create random floating-point values between 0.0 and 1.0, call np.random.random. For example:

import numpy as np
random_floats_between_0_and_1 = np.random.random([6])
print(random_floats_between_0_and_1)

[0.79637156 0.50214405 0.48019723 0.36085443 0.93974152 0.42197657]


In [17]:
#  Mathematical Operations on NumPy Operands -->
# If you want to add or subtract two arrays, linear algebra requires 
# that the two operands have the same dimensions. Furthermore, 
# if you want to multiply two arrays, linear algebra imposes strict 
# rules on the dimensional compatibility of operands. Fortunately, 
# NumPy uses a trick called broadcasting to virtually expand the 
# smaller operand to dimensions compatible for linear algebra. 
# For example, the following operation uses broadcasting to add 2.0 
# to the value of every item in the array created in the previous 
# code cell: 

import numpy as np
random_float_between_2_and_3 = random_floats_between_0_and_1 + 2.0
print(random_float_between_2_and_3)

[2.79637156 2.50214405 2.48019723 2.36085443 2.93974152 2.42197657]


In [23]:
# The following operation also relies on broadcasting to multiply each cell in an array by 3:

random_integers_between_150_and_300 = random_integers_between_50_and_100 * 3
print(random_integers_between_150_and_300)

[153 189 195 261 162 255]


In [24]:
feature = np.arange(6, 20)
print(feature)
label = (feature * 3) + 4
print(label)




[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[22 25 28 31 34 37 40 43 46 49 52 55 58 61]


In [27]:
noise = (np.random.random([15] * 4)) - 2
print(noise)
label = label + noise
print(label)

[[[[-1.32247618 -1.36524463 -1.74295772 ... -1.31429159 -1.23039164
    -1.59724744]
   [-1.83456996 -1.72723792 -1.26294079 ... -1.35167176 -1.79233067
    -1.33320985]
   [-1.58113575 -1.69870347 -1.72831657 ... -1.28106347 -1.73531834
    -1.0999198 ]
   ...
   [-1.29007113 -1.82948828 -1.81877328 ... -1.62565204 -1.2163376
    -1.50775537]
   [-1.09298911 -1.14363047 -1.72341669 ... -1.03784493 -1.66503766
    -1.48180922]
   [-1.36006681 -1.38829467 -1.46709903 ... -1.28363979 -1.63349335
    -1.9494728 ]]

  [[-1.26694054 -1.48002815 -1.31018365 ... -1.01837396 -1.23186233
    -1.77336708]
   [-1.76229837 -1.62532489 -1.94656994 ... -1.61764488 -1.97047443
    -1.51589386]
   [-1.83925254 -1.68643686 -1.34977411 ... -1.78235152 -1.28095728
    -1.85444944]
   ...
   [-1.18957363 -1.86699987 -1.15026647 ... -1.76630398 -1.12505782
    -1.92418822]
   [-1.45979233 -1.09718382 -1.66484218 ... -1.47347149 -1.77099502
    -1.26547053]
   [-1.55887905 -1.25185593 -1.65820629 ... -1.943

ValueError: operands could not be broadcast together with shapes (14,) (15,15,15,15) 

In [3]:
# Import relevant modules
# The first code cell imports the necessary modules and sets a few display options

import numpy as np
import pandas as pd
import tensorflow as tf
from matplotlib import pyplot as plt

pd.options.display.max_rows = 10
# pd.options.display.float_format = "{:.1f}"

ModuleNotFoundError: No module named 'tensorflow'